### ISSUE TITLE
Support for null in $filter eq query

### ISSUE THREAD

**Issue by uythoang** [RESOStandards/RESO-WebAPI-Client-dotNet#11]
### Description

For Intermediate.Coformance.100701, shouldn't this test be able to handle null values? For example, all of our members have null for MemberCountyOrParish. However, the RESO test for 100701 calls this endpoint `/api/reso/odata/Member?$filter=MemberCountyOrParish eq` when it should be `/api/reso/odata/Member?$filter=MemberCountyOrParish eq null`.

Due to this, the test fails even though we believe OData specs allow for filtering primitive literals like strings with a null value: http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#_Toc505773287

**Comment by sschuessler** [comment]
Please email your Client Settings file to Greg and we can take a look.

Remember that the query supports the word 'null' and not an actual null.

https://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/abnf/odata-abnf-construction-rules.txt

nullValue = 'null' 

Also, not sure if this matters in this case but we are currently on v4.00 not v4.01.

Stuart

**Comment by mrabanda** [comment]
@sschuessler I'm working with @uythoang on this and we can't find anywhere in the OData standard that makes reference to `null` with single quotes in a `$filter` query.

In the OData URL Conventions doc there are only references to `eq null` without quotes, which is defined here: http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_PrimitiveLiterals (this is v4.01 but the section is the same in v4.0)

This is actually accurate with the `OData-ABNF` you've mentioned because in the document single quotes refer to the exact characters as they should appear in the url while double quotes refer to string values.

For Example:

Rules `nullValue = 'null'` and  `eqExpr = RWS 'eq' RWS commonExpr` refer to `null` and `eq` in single quotes, hence the system query part of a compliant URL would look like like `$filter=MemberCountyOrParish eq null` without quotes around `eq` or `null`.

Per this example and OData URL convention, if `null` was in single quotes the service would have to compare `MemberCountyOrParish` to STRING `"null"` instead of VALUE `null`.

**Comment by sschuessler** [comment]
The BNF states that it is a text null because it is in the URL.  I am not sure why the test is failing.  Please send over you Client Settings to Greg so we can take a look.
